### ISSUE TITLE
WIFI module not showing up

### ISSUE THREAD

**Issue by Biprodeep** [nguiard/archlinux-orange-pi-zero#1]
Nov 15 02:53:11 alarm systemd[1]: Starting Networking for netctl profile wireles
Nov 15 02:53:11 alarm network[270]: Starting network profile 'wireless-home'...
Nov 15 02:53:11 alarm network[270]: Interface 'wlan0' does not exist
Nov 15 02:53:11 alarm network[270]: Failed to bring the network up for profile '
Nov 15 02:53:11 alarm systemd[1]: netctl@wireless\x2dhome.service: Main process 
Nov 15 02:53:11 alarm systemd[1]: netctl@wireless\x2dhome.service: Failed with r
Nov 15 02:53:11 alarm systemd[1]: Failed to start Networking for netctl profile

**Comment by nguiard** [comment]
Hi, yeah I read somewhere that there's no support for the wifi module used on that board because it is unreliable and people dropped efforts trying to support it. I dont remember the source though. If you need wifi, you're better off with another board, make sure to note the wifi chip when selecting it and see if it's supported by drivers :)

**Comment by Biprodeep** [comment]
Hey, happy to announce that I finally solved the problem myself by recompiling the kernel with the the given sunxi firmwares. Thanks anyway!

**Comment by IronJaeger** [comment]
@Biprodeep hi, can you please show me or point me to a guide how to do it ? thanks

**Comment by falahati1987** [comment]
guys, 
I can't figure out how to enable wifi on OPi Zero H2+.
I can't compile this: https://github.com/jwrdegoede/rtl8189ES_linux

Any suggestions?
