### ISSUE TITLE
uptime ?

### ISSUE THREAD

**Issue by francois-auclair** [nguiard/archlinux-orange-pi-zero#2]
Hey

Thanks for doing this, what your uptime like with archlinux?
I'm using the Ubuntu image the OrangePi keeps dropping and needs to be restarted. I'm wondering if it's better with ArchLinux

**Comment by nguiard** [comment]
Hi, your problem might come from a power brick that's not powerful and stable enough. You may want to try a better one (5V 3A should work for sure), with a good cable too. I basically have zero downtime. One is running since december in a family house and didn't drop since.
However if you know it's not power related, I don't know, you might want to try Arch yeah, but right now I don't know why Ubuntu would drop. Might be a bad unit too.

**Comment by IronJaeger** [comment]
I have drops too, with this image. it varies between 3 days and a week afaik. my power supply is nowhere near reliable though. I'll be checking that. I hope there will be an updated image with wifi supported soon :)
